export enum PATHS {
    ROOT = '/',
    MAIN = '/main',
    AUTH = '/auth',
    REGISTRATION = '/auth/registration',
    CONFIRM_EMAIL = '/auth/confirm-email',
    CHANGE_PASSWORD = '/auth/change-password',
    ERROR_LOGIN = '/result/error-login',
    REGISTRATION_SUCCESS = '/result/success',
    ERROR_USER_EXIST = '/result/error-user-exist',
    ERROR = '/result/error',
    EMAIL_NO_EXIST = '/result/error-check-email-no-exist',
    ERROR_CHECK_EMAIL = '/result/error-check-email',
    ERROR_CHANGE_PASSWORD = '/result/error-change-password',
    SUCCESS_CHANGE_PASSWORD = '/result/success-change-password',
}
